-- 014_multimodal_rag.sql: Estrutura para RAG Multimodal (Imagens de Páginas)

-- 1. STORAGE BUCKET: manual-pages
-- (O bucket deve ser criado via dashboard ou via insert na tabela storage.buckets se tiver permissão)
-- Tentativa de criação via SQL (pode falhar dependendo das permissões do postgres role, mas é o padrão)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('manual-pages', 'manual-pages', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas de Storage para manual-pages
-- Public Read
DROP POLICY IF EXISTS "Public Read Manual Pages" ON storage.objects;
CREATE POLICY "Public Read Manual Pages"
ON storage.objects FOR SELECT
TO public
USING ( bucket_id = 'manual-pages' );

-- Authenticated Upload (Admin logic will be handled by App, allowing auth users for MVP or restricting to Admin)
DROP POLICY IF EXISTS "Auth Upload Manual Pages" ON storage.objects;
CREATE POLICY "Auth Upload Manual Pages"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'manual-pages' );

-- Authenticated Delete (Admin only ideally, but keeping symmetric for now)
DROP POLICY IF EXISTS "Auth Delete Manual Pages" ON storage.objects;
CREATE POLICY "Auth Delete Manual Pages"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'manual-pages' );


-- 2. TABLE: manual_pages_embeddings
CREATE TABLE IF NOT EXISTS public.manual_pages_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manual_id UUID REFERENCES public.technical_manuals(id) ON DELETE CASCADE,
  page_number INT NOT NULL,
  image_path TEXT NOT NULL, -- Caminho no storage ex: manual_id/page_1.jpg
  image_description TEXT,   -- Descrição gerada pela Vision AI
  embedding vector(1536),   -- Vetor da descrição (OpenAI small-3 compatível)
  metadata JSONB,           -- Extras
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS
ALTER TABLE public.manual_pages_embeddings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Read Pages Embeddings" ON public.manual_pages_embeddings;
CREATE POLICY "Read Pages Embeddings"
ON public.manual_pages_embeddings FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Write Pages Embeddings" ON public.manual_pages_embeddings;
CREATE POLICY "Write Pages Embeddings"
ON public.manual_pages_embeddings FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- 3. FUNCTION: match_manual_pages
-- Busca híbrida/similaridade nas descrições das páginas
create or replace function match_manual_pages (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  manual_id uuid,
  page_number int,
  image_path text,
  image_description text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    mpe.id,
    mpe.manual_id,
    mpe.page_number,
    mpe.image_path,
    mpe.image_description,
    1 - (mpe.embedding <=> query_embedding) as similarity
  from manual_pages_embeddings mpe
  where 1 - (mpe.embedding <=> query_embedding) > match_threshold
  order by mpe.embedding <=> query_embedding
  limit match_count;
end;
$$;
